CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS requests;
CREATE SCHEMA IF NOT EXISTS residents;
CREATE SCHEMA IF NOT EXISTS appliances;
CREATE SCHEMA IF NOT EXISTS consumables;
CREATE SCHEMA IF NOT EXISTS notifications;
CREATE SCHEMA IF NOT EXISTS reports;