spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dormitory}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: residents-hikari
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: residents
        jdbc:
          time_zone: UTC
#        query:
#          plan_cache_max_size: 0
#          plan_cache_parameter_metadata_max_size: 0

    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: residents
