springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: alpha
    urls:
      - name: auth-service
        url: /v3/api-docs/auth
      - name: residents-service
        url: /v3/api-docs/residents
      - name: requests-service
        url: /v3/api-docs/requests
      - name: appliances-service
        url: /v3/api-docs/appliances
      - name: consumables-service
        url: /v3/api-docs/consumables
      - name: notifications-service
        url: /v3/api-docs/notifications
      - name: reports-service
        url: /v3/api-docs/reports
