spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dormitory
  data:
    redis:
      host: localhost
  kafka:
    bootstrap-servers: localhost:9092

integration:
  auth:
    url: http://localhost:8081

logging:
  level:
    ru.dstu.dormitory.residents_service: DEBUG
