CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS user_schema;
CREATE SCHEMA IF NOT EXISTS dormitory_schema;
CREATE SCHEMA IF NOT EXISTS request_schema;
CREATE SCHEMA IF NOT EXISTS notification_schema;
