{
 "title": "auth-service",
 "description": "Логгирование микросервиса auth-service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Соотношение уровней логов",
   "type": "piechart",
   "description": "Круговая диаграмма — сколько INFO, WARN, ERROR. auth service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({app=\"auth-service\"} [1h]))"
    }
   ]
  },
  {
   "title": "Только ошибки",
   "type": "logs",
   "description": "Только ошибки auth-service",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"auth-service\", level=\"ERROR\"}"
    }
   ]
  },
  {
   "title": "Ошибки во времени",
   "type": "timeseries",
   "description": "График ошибок для визуализации пиков auth-service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({app=\"auth-service\", level=\"ERROR\"} [1m])"
    }
   ]
  },
  {
   "title": "Auth Service Monitoring",
   "type": "logs",
   "description": "все логи Auth-Service",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"auth-service\"}"
    }
   ]
  },
  {
   "title": "Счётчик входов за час",
   "type": "stat",
   "description": "Счётчик входов за час auth-service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({app=\"auth-service\"} |= \"вошёл\" [1h])"
    }
   ]
  },
  {
   "title": "Регистрация",
   "type": "logs",
   "description": "Запросы пользователей на регистрацию auth-service",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{app=\"auth-service\"} |= \"регистрацию\""
    }
   ]
  }
 ]
}