spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dormitory}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: consumables-hikari
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: consumables
        jdbc:
          time_zone: UTC
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: consumables
